

# This file was *autogenerated* from the file HFK-m.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_2 = Integer(2)
from tqdm import tqdm
import snappy

f = open("numDTList.txt", "r")
numDTList = f.readlines()
f.close()

mList=[]
tauList=[]
epsilonList=[]
HFKrankList=[]

for k in tqdm(range(_sage_const_0 ,len(numDTList))):
    K=snappy.Link('DT: [('+numDTList[k].strip("\n")+')]')
    S=K.knot_floer_homology()
    tau = S['tau']
    epsilon = S['epsilon']
    HFKrank = S['total_rank']
    m = _sage_const_2 *tau - epsilon
    mList.append(str(m))
    tauList.append(str(tau))
    epsilonList.append(str(epsilon))
    HFKrankList.append(str(HFKrank))

with open('mList.txt','w') as outfile: 
    outfile.write('\n'.join(mList))  

with open('tauList.txt','w') as outfile: 
    outfile.write('\n'.join(tauList)) 

with open('epsilonList.txt','w') as outfile: 
    outfile.write('\n'.join(epsilonList))    

with open('HFboundList.txt','w') as outfile: 
    outfile.write('\n'.join(HFKrankList))

