

# This file was *autogenerated* from the file HFK-nBounds.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2)
f = open('mList.txt', 'r')
mList = f.readlines()
f.close()

f = open('HFboundList.txt', 'r')
HFKrankList = f.readlines()
f.close()

nBoundList = []

#for k in range(0,len(HFKlines)):
#    if (k % 100000 == 0):
#        print(k/23432930)
#    if HFKlines[k].startswith("Total rank : "):
#        HFKrankList.append(HFKlines[k].replace("Total rank : ","").strip("\n"))

#for k in range(0,2000+0*len(HFKlines)):
#if HFKlines[k].startswith("Total rank : "):
#HFKrankList.append(HFKlines[k].replace("Total rank : ","").strip("\n"))

#with open('HFKrankList.txt', 'w') as outfile:
#    outfile.write("\n".join(HFKrankList))



for k in range(_sage_const_0 ,len(HFKrankList)):
    m = int(mList[k].strip("\n"))
    if abs(m) > _sage_const_1 :
        nBound = floor((int(HFKrankList[k])+abs(m)-_sage_const_2 )/_sage_const_2 )
    else:
        nBound = floor((int(HFKrankList[k])-_sage_const_1 )/_sage_const_2 )
    nBoundList.append(str(nBound))

#for k in range(0,len(HFKrankList)):
#m = int(mList[k].strip("\n"))
#nBound = floor((int(HFKrankList[k])-1)/2)
#if abs(m) > 1:
#nBound = floor((int(HFKrankList[k])+abs(m)-2)/2)
#nBoundList.append(str(nBound))

with open('nList.txt', 'w') as outfile:
    outfile.write("\n".join(nBoundList))

print("COMPLETED WRITING nLIST")

