

# This file was *autogenerated* from the file run_casson_only.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2000 = Integer(2000)
import sys
import yaml 
from pathlib import Path
import sympy as sym

# Set BASE to current directory
BASE = Path(".").resolve()
sys.path.append(str(BASE))

from surgeries_dbc.io import load_knot_records, write_hf_outputs
from surgeries_dbc.hf_casson import attach_hf_data
from surgeries_dbc.hf_filter import hf_filter, write_hf_fail_list
from surgeries_dbc.casson_only import run_casson_on_candidates

print(f"=== Casson-only pipeline (running in {BASE}) ===")

# ---------------------------------------------------------------------
# Step 1: Load knot records (names)
# ---------------------------------------------------------------------
print("[Step 1] Loading knot records...")
records = load_knot_records(BASE)
n_knots = len(records)
print(f"[Step 1] Loaded {n_knots} knots.")

# ---------------------------------------------------------------------
# Step 1.5: Load Alphabetic DT Codes (DTList.txt)
# ---------------------------------------------------------------------
dt_alpha_path = BASE / "DTList.txt"
if not dt_alpha_path.exists():
    raise FileNotFoundError(f"DTList.txt not found in {BASE}")

dt_alpha_lines = dt_alpha_path.read_text().splitlines()

if len(dt_alpha_lines) != n_knots:
    # Warning only, in case of empty trailing lines, but ideally they match exactly
    print(f"WARNING: DTList.txt has {len(dt_alpha_lines)} lines, expected {n_knots}.")

print("[Step 1.5] Alphabetic DT codes loaded.")

# ---------------------------------------------------------------------
# Step 2: Load determinants det(K) from detList.txt
# ---------------------------------------------------------------------
det_path = BASE / "detList.txt"
if not det_path.exists():
    raise FileNotFoundError(f"detList.txt not found in {BASE}")

det_lines = det_path.read_text().splitlines()
if len(det_lines) != n_knots:
    raise ValueError(f"detList.txt length {len(det_lines)} != records {n_knots}.")

for rec, d_s in zip(records, det_lines):
    rec.det = int(d_s.strip())

print("[Step 2] Determinants loaded.")

# ---------------------------------------------------------------------
# Step 3: Attach HF data (m, n, HFbound)
# ---------------------------------------------------------------------
print("[Step 3] Attaching HF data...")
attach_hf_data(BASE, records)
print("[Step 3] HF data attached.")

# ---------------------------------------------------------------------
# Step 4: HF-only filter -> hf_candidates
# ---------------------------------------------------------------------
print("[Step 4] Running HF-only filter...")
hf_log, hf_candidates = hf_filter(records)
write_hf_fail_list(BASE, records, hf_candidates)

hf_survivor_count = len(hf_candidates)
print(f"[Step 4] HF-surviving knots: {hf_survivor_count}")

# ---------------------------------------------------------------------
# Step 5: Load classical invariants ONLY for HF-survivors
# ---------------------------------------------------------------------
if hf_survivor_count > _sage_const_0 :
    print("[Step 5] Loading classical invariants for HF-survivors...")

    a_path      = BASE / "aList.txt"
    sig_path    = BASE / "sigList.txt"
    jones_path  = BASE / "jonesList.txt"
    casson_path = BASE / "cassonList.txt"

    def _load_list_or_die(path: Path, n: int) -> list[str]:
        if not path.exists():
            raise FileNotFoundError(f"{path.name} not found in {BASE}")
        lines = path.read_text().splitlines()
        if len(lines) != n:
            raise ValueError(f"{path.name} length mismatch.")
        return lines

    a_lines      = _load_list_or_die(a_path, n_knots)
    sig_lines    = _load_list_or_die(sig_path, n_knots)
    jones_lines  = _load_list_or_die(jones_path, n_knots)
    casson_lines = _load_list_or_die(casson_path, n_knots)

    hf_indices = sorted(hf_candidates.keys())

    for count, idx in enumerate(hf_indices, start=_sage_const_1 ):
        rec = records[idx]
        a_s    = a_lines[idx].strip()
        sig_s  = sig_lines[idx].strip()
        j_s    = jones_lines[idx].strip()
        cass_s = casson_lines[idx].strip()

        if a_s == "" or sig_s == "" or j_s == "" or cass_s == "":
            raise ValueError(f"Missing data for {rec.name} at index {idx}")

        rec.A          = sym.sympify(a_s)
        rec.signature  = int(sig_s)
        rec.jones_expr = sym.sympify(j_s)
        rec.casson_dbc = sym.sympify(cass_s)
        
        if count % _sage_const_2000  == _sage_const_0 :
            print(f"  Attached invariants for {count} / {hf_survivor_count}...")

    print("[Step 5] Classical invariants attached.")

# ---------------------------------------------------------------------
# Step 6: Casson comparison
# ---------------------------------------------------------------------
casson_log = []
casson_data = {} 

if hf_survivor_count > _sage_const_0 :
    print("[Step 6] Running Casson comparison...")
    casson_log, casson_data = run_casson_on_candidates(records, hf_candidates)
    
    full_log = hf_log + casson_log
    write_hf_outputs(BASE, records, full_log)
    print("[Step 6] Text logs written.")
else:
    print("[Step 6] No HF survivors, skipping Casson calc.")

# ---------------------------------------------------------------------
# Step 7: Generate YAML Summary
# ---------------------------------------------------------------------
print("[Step 7] Generating casson_summary.yaml...")

yaml_output = []

for idx, rec in enumerate(records):
    pass_hf = (idx in hf_candidates)
    
    # Retrieve Casson results if they exist (list of dicts)
    results = casson_data.get(idx, [])
    
    # Retrieve Alphabetic DT Code from list loaded in Step 1.5
    # Use empty string if index out of bounds (though it shouldn't be)
    dt_alpha = dt_alpha_lines[idx] if idx < len(dt_alpha_lines) else "Unknown"
    
    entry = {
        "knotname": rec.name,
        "DT_code": dt_alpha.strip(),
        "pass_fail_HF_check": pass_hf,
        "CASSON_COMPARISON_RESULTS": results
    }
    
    yaml_output.append(entry)

yaml_path = BASE / "casson_summary.yaml"
with open(yaml_path, "w") as f:
    yaml.dump(yaml_output, f, sort_keys=False)

print(f"[Step 7] YAML written to {yaml_path}")
print("=== Casson-only pipeline complete ===")

