

# This file was *autogenerated* from the file run_pipeline.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0)
import sys
from pathlib import Path

BASE = Path(".").resolve()
sys.path.append(str(BASE))

from surgeries_dbc.io import (
    load_knot_records,
    write_classical_lists,
    load_classical_lists,
    write_hf_outputs,
)
from surgeries_dbc.invariants import compute_classical_invariants
from surgeries_dbc.hf_casson import attach_hf_data, run_hf_casson
from surgeries_dbc.tv_compare import run_tv_compare

fail_list_path = BASE / "failList.txt"

if fail_list_path.exists():
    print("=== Fast path: failList.txt found, skipping stages 1–3 ===")
    tv_ok = run_tv_compare(BASE)
    if tv_ok:
        print("=== Turaev–Viro stage complete ===")
    else:
        print("=== Turaev–Viro stage halted early; re-run to continue. ===")
    sys.exit(_sage_const_0 )

print("=== Stage 1: DT conversion ===")
num_dt_path = BASE / "numDTList.txt"

if num_dt_path.exists():
    print("numDTList.txt already exists; skipping.")
else:
    print("numDTList.txt not found; running DT-convert.sage...")
    load("DT-convert.sage")

print("=== Stage 2: Classical invariants ===")
records = load_knot_records(BASE)

paths = [BASE / f for f in ["detList.txt", "aList.txt", "sigList.txt", "jonesList.txt", "cassonList.txt"]]
have_classical = all(p.exists() for p in paths)

if have_classical:
    print("Classical invariant lists already exist; loading.")
    load_classical_lists(BASE, records)
else:
    print("Classical invariant lists missing; computing...")
    compute_classical_invariants(records)
    write_classical_lists(BASE, records)

print("=== Stage 3: HF + Casson comparison ===")
if not fail_list_path.exists():
    print("Running HF + Casson comparison...")
    attach_hf_data(BASE, records)
    output_log = run_hf_casson(records)
    write_hf_outputs(BASE, records, output_log)
else:
    print("failList.txt exists; skipping.")

print("=== Stage 4: Turaev–Viro comparison ===")
tv_ok = run_tv_compare(BASE)

if tv_ok:
    print("=== Pipeline complete ===")
else:
    print("=== Pipeline halted early; re-run to continue. ===")

