

# This file was *autogenerated* from the file run_det_pipeline.sage
from sage.all_cmdline import *   # import sage library

import sys
from pathlib import Path

# Set BASE to the current directory
BASE = Path(".").resolve()
sys.path.append(str(BASE))

from surgeries_dbc.io import load_knot_records
from surgeries_dbc.invariants_det_only import compute_determinants

num_dt_path = BASE / "numDTList.txt"
det_path = BASE / "detList.txt"

print(f"=== Determinant-only pipeline (running in {BASE}) ===")

# ---------------------------------------------------------------------
# Step 1: Ensure numDTList.txt exists
# ---------------------------------------------------------------------

if num_dt_path.exists():
    print("numDTList.txt already exists; using existing numeric DT codes.")
else:
    print("numDTList.txt not found; running DT-convert.sage...")
    # Assumes DT-convert.sage is in the current directory
    load("DT-convert.sage")

# ---------------------------------------------------------------------
# Step 2: Load knot records (name, DTList, numDTList)
# ---------------------------------------------------------------------

print("Loading knot records from:", BASE)
records = load_knot_records(BASE)
print(f"Loaded {len(records)} knots.")

# ---------------------------------------------------------------------
# Step 3: Compute determinants
# ---------------------------------------------------------------------

print("Computing determinants det(K) = |Δ_K(-1)| ...")
compute_determinants(records)

# ---------------------------------------------------------------------
# Step 4: Write detList.txt
# ---------------------------------------------------------------------

print("Writing detList.txt ...")
det_lines = [str(rec.det) for rec in records]
det_path.write_text("\n".join(det_lines))

print("Done. detList.txt written to", det_path)

